spring:
  profiles:
    active: dev # ????? dev ???? ??
  output:
    ansi:
      enabled: always # ?? ?? ??
  thymeleaf:
    cache: false # ???? ?? ??
    prefix: classpath:/templates/
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/qna_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ??: none, validate, update, create, create-drop
    properties:
      hibernate:
        show_sql: true # ???? SQL ?? ??
        format_sql: true # ???? SQL? ???
        use_sql_comments: true
  # LOGGING
  logging:
    level:
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE